### ISSUE TITLE
OS Version does not contain the total number

### ISSUE THREAD

**Issue by likudo** [jdegene/steamHWsurvey#4]
![2023-12-09_010920](https://github.com/jdegene/steamHWsurvey/assets/12607165/1b60dae9-e7d0-4aff-8666-f04855d666f6)

The sum of macOS in the raw data is 0.82% as you can see.

But the total share of OSX should be 1.53% at the moment (2023 Nov)
[https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam](url)

It seems CSV only contains the first 5 MacOS versions but not the rest,
(maybe other categories too)

so we can not find out the total number of MacOS percentages from the raw data

**Comment by jdegene** [comment]
Thanks for flagging this, I'll add a disclaimer.

The reason behind this is because Steam doesn't give us all OS versions they are actually seeing in their survey (the Windows percentages also don't add up to 100%). Also, I'm only crawling the main page.

If you have a look at the "Mac Only" page, they actually include the option "other" which corresponds to the missing 0.71% that are missing from the main page
![Clipboard01](https://github.com/jdegene/steamHWsurvey/assets/17744939/ec5da3d4-27a6-4067-9631-1212dffa8364)
